name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.3.0'

dependencies:
  cached_network_image: ^3.2.2
  carousel_slider: ^4.1.1
  cloud_firestore: ^4.0.2
  country_picker: ^2.0.16
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  intl: ^0.17.0
  shimmer: ^2.0.0
  url_launcher: ^6.1.5
  uuid: ^3.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash_screen.png"

flutter_native_splash:
  color: "#185d4e"
  image: assets/splash_screen.png

  android12:
    image: assets/splash_screen.png
    color: "#185d4e"
    icon_background_color: "#185d4e"

flutter:
  uses-material-design: true
  assets:
     - assets/svgs/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
